feat: update Datagrid filter to account for reoccuring metadata columns
determined-ai/determined pull request #10046
Opened 2024-10-11 19:01 UTC by thiagodallacqua-hpe

## Ticket

[ET-790](https://hpe-aiatscale.atlassian.net/browse/ET-790)

## Description

Right now, if we have multiple metadata columns with the same name, there's no quick way of knowing of which type each one is while selecting it. This PR intends to add a descriptive text next to duplicate entries for the metadata columns.

## Test Plan

- make sure that you have at least one metadata column that is duplicated and of a different type
- go to a experiment list
  - make sure that the grid visualization is enabled
- open the filter
- scroll down for the metadata column options
- verify that the duplicates has a `<column_name> <column_type_tag>` format

<img width="1480" alt="Screenshot 2024-10-14 at 16 58 13" src="https://github.com/user-attachments/assets/94b28e84-718b-400b-a587-cf839c4c0577">

<img width="1481" alt="Screenshot 2024-10-14 at 16 59 27" src="https://github.com/user-attachments/assets/8a003186-8649-4b67-abd4-3f914474689e">

<img width="801" alt="Screenshot 2024-10-18 at 20 04 36" src="https://github.com/user-attachments/assets/fefac217-2cf2-4f08-86d4-3a6e8d27a4f9">

![Screenshot 2024-10-14 at 15 59 55](https://github.com/user-attachments/assets/a948fd86-ca75-4a8e-950a-c289f6e680ba)

## Checklist

- [ ] Changes have been manually QA'd
- [ ] New features have been approved by the corresponding PM
- [ ] User-facing API changes have the "User-facing API Change" label
- [ ] Release notes have been added as a separate file under `docs/release-notes/`
  See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-notes/README.md) for details.
- [ ] Licenses have been included for new code which was copied and/or modified from any external code

[ET-790]: https://hpe-aiatscale.atlassian.net/browse/ET-790?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DET-123]: https://hpe-aiatscale.atlassian.net/browse/DET-123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-10-17 21:10 UTC, keita-determined requested changes
we want to show types in all column names

2024-10-18 17:35 UTC, keita-determined requested changes

2024-10-18 17:35 UTC, keita-determined commented on webui/react/src/services/types.ts
> +export interface PostRunMetadata {
its not used anywhere. why do we need this?

2024-10-18 17:35 UTC, keita-determined commented on webui/react/src/components/FilterForm/components/FilterField.tsx
> +  useEffect(() => {
i dont think we need to use useEffect here. can we get rid of it

2024-10-18 22:11 UTC, keita-determined requested changes
could you double-check the ticket? i think specs around separator etc are not follwoing the ticket description.

2024-10-21 20:45 UTC, keita-determined commented on webui/react/src/components/FilterForm/components/FilterFormStore.ts
> +        if (form.type === col.type && form.location === col.location) return form;
i dont think this improves the readability. can we just write the conditions in the same if statement?

2024-10-22 19:06 UTC, keita-determined requested changes
Deuplicate metadata arent listed in the filter

2024-10-23 19:54 UTC, ashtonG commented on webui/react/src/utils/flatRun.ts
> +/// wanna know why this separator is used? see https://hpe-aiatscale.atlassian.net/browse/ET-785
please include the reason for this inline -- links rot.

2024-10-23 20:26 UTC, ashtonG commented on webui/react/src/components/FilterForm/components/FilterField.tsx
> +  );
this should be updated for the metadata columns, no?

2024-10-24 14:28 UTC, ashtonG commented
could you rebase this such that `thiago/ET-790` is on `thiago/ET-791`? i'm having trouble testing the sort fix because this branch doesn't have the hew updates but it does change the location of `formatColumnKey`.

2024-10-24 17:17 UTC, keita-determined reviewed
This PR includes some other changes. there is a conflict. That'd be great to fix them.

2024-10-24 18:28 UTC, keita-determined requested changes
the same name metadata columns with different types are not shown in the filter.

2024-10-24 18:28 UTC, keita-determined commented on webui/react/src/components/FilterForm/components/FilterField.tsx
> +    const [type, newColName] = (value?.toString() ?? '').split(METADATA_SEPARATOR, 2);
i know the meaning. i wonder why its 2 instead of 1

2024-10-24 18:28 UTC, keita-determined commented on webui/react/src/utils/flatRun.ts
> +export const METADATA_SEPARATOR = '\u241F' as const;
this separator is not just for metadata

```suggestion
export const COLUMN_SEPARATOR = '␟';
```

2024-10-24 20:27 UTC, keita-determined commented
> @keita-determined it turns out that array-typed columns are banned from the filters
> 
> ```ts
> const bannedFilterColumns: Set<string> = useMemo(() => {
>     return new Set([...BANNED_FILTER_COLUMNS, ...arrayTypeColumns]);
>   }, [arrayTypeColumns]);
> ```

i know its banned. but when there are metadata with the same name and different type, the metadata won't display in the filter.

2024-10-24 20:36 UTC, keita-determined commented on webui/react/src/utils/flatRun.ts
> +export const METADATA_SEPARATOR = '\u241F' as const;
its not fixed here.

2024-10-25 18:39 UTC, ashtonG commented on webui/react/src/components/FilterForm/components/FilterField.tsx
> +    const [type, newColName] = (value?.toString() ?? '').split(METADATA_SEPARATOR, 2);
if it were 1, it would only output an array with length 1.

2024-10-31 19:14 UTC, ashtonG reviewed
update the table filter tests -- it seems that they check the label text and now it's failing.

2024-11-05 16:21 UTC, closed without merging