chore: webui react storybook for StateSelectFilter component [DET-4039]
determined-ai/determined pull request #1252
Opened 2020-09-04 08:06 UTC by apizzini

## Description

This PR addresses the request of DET-4039 JIRA issue.
Note that storybooks are still not working on master due to serverAddress issue (addressed in this PR: https://github.com/determined-ai/determined/pull/1240/commits).

## Test Plan

Storybook working fine.

## Commentary (optional)

Screenshots:
![Schermata 2020-09-04 alle 10 04 30](https://user-images.githubusercontent.com/5413702/92216068-1602aa80-ee96-11ea-9bc4-d99015930304.png)
![Schermata 2020-09-04 alle 10 04 36](https://user-images.githubusercontent.com/5413702/92216075-18650480-ee96-11ea-8a39-8aeb60af7faa.png)

## Checklist

- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
See [Release Note](../docs/release-notes/README.md) for details.

2020-09-14 16:40 UTC, hkang1 requested changes
I just realized that `onChanges` should not be required on the `StateSelectfilter` based on the stories you wrote. Would you mind updating `StateSelectFilter` to make `onChange` prop optional so we don't need to pass in a blank function? 🙏

2020-09-15 06:50 UTC, apizzini commented
@hkang1 changed `StateSelectfilter` to make `onChanges ` optional.

2020-09-15 23:15 UTC, hkang1 commented on webui/react/src/components/StateSelectFilter.stories.tsx
> +  <StateSelectFilter />
Thinking the same task as the `UserSelectFilter` of adding `onChange` event to this story, just to test and preserve the state of the selected value (user).

2020-09-16 06:57 UTC, hkang1 approved these changes
LGTM! 🎉

2020-09-17 16:29 UTC, merged