fix: learning curve tuning [DET-4375, DET-4711]
determined-ai/determined pull request #1753
Opened 2021-01-05 23:52 UTC by hkang1

## Description

Tuning Learning Curve

- Thicken the learning curve. Previously the lines are a bit too thin.
- Add glasbey color palette for the learning curve series.
- Add glasbey color palette for the learning curve trial hp table.

Fixes

- When you hover out of a highlighted learning curve series, it keeps the corresponding trial table row highlighted. Update to correct this bug.
 

## Test Plan

## Commentary (optional)

## Checklist

- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
See [Release Note](../docs/release-notes/README.md) for details.

2021-01-09 00:59 UTC, hamidzr requested changes
LGTM. 

highlighting some trial isn't that distinctive. I scrolled over a row and was expecting to find the trial highlighted but it wasn't easy to tell. with some colors, it works great. here one is highlighted:
![Screen Capture_select-area_20210108164949](https://user-images.githubusercontent.com/12127420/104078318-46ef4500-51d2-11eb-9b43-e241238f5f93.png)



![Screen Capture_select-area_20210108165456](https://user-images.githubusercontent.com/12127420/104078314-435bbe00-51d2-11eb-9a11-75e284c0ca30.png)

suggestion: Hyperparameter visua..
@ahj-determined any wording suggestions here? or maybe we link to the searcher section http://localhost:8080/docs/reference/experiment-config.html#searcher 

this looks like a good place to advertise for hp search

2021-01-09 00:59 UTC, hamidzr commented on webui/react/src/pages/ExperimentDetails/ExperimentVisualization/LearningCurve.tsx
> +          popout
blocking: these need `external` tags otherwise won't work

2021-01-09 01:04 UTC, hamidzr commented
added comment about whether we want to add the new color scheme to overview and maybe the existing experiment page.

2021-01-09 01:05 UTC, hamidzr commented
![Screen Capture_select-area_20210108170416](https://user-images.githubusercontent.com/12127420/104078566-ae59c480-51d3-11eb-92b7-c00718f376bb.png)

2021-01-09 01:11 UTC, hamidzr commented
a bunch of nits

- highlighting (from plot to row) only happens on dots
- jagged line, blurry. can we up the resolution? is uplot canvas based? 
250%
![Screen Capture_select-area_20210108170918](https://user-images.githubusercontent.com/12127420/104078689-435cbd80-51d4-11eb-95a8-1a2264ebbd40.png)
  - maybe an option would be move the axis labels out of the chart later if we want it to match the rest of the page easier.
100%
![Screen Capture_select-area_20210108170653](https://user-images.githubusercontent.com/12127420/104078653-18726980-51d4-11eb-826a-4c5e907bf089.png)


- zoom between the data points and you don't see any lines. this is understandable but could it be confusing?

2021-01-09 01:13 UTC, hamidzr commented
nit: chart and the trial hyperparameters table rerender visibly on changing the metric or number of top trials

2021-01-10 06:17 UTC, ahj-determined commented
> @ahj-determined any wording suggestions here? or maybe we link to the searcher section http://localhost:8080/docs/reference/experiment-config.html#searcher

Yeah, I like those two ideas. How about something like:

Hyperparameter visualizations are not applicable for single trial experiments.
Learn about [how to run a hyperparameter search](https://docs.determined.ai/latest/how-to/hyperparameter-tuning.html?highlight=hyperparameter%20search).

2021-01-11 17:12 UTC, hkang1 commented on webui/react/src/pages/ExperimentDetails/ExperimentVisualization/LearningCurve.tsx
> +          popout
good catch, thanks!

2021-01-11 17:21 UTC, hkang1 commented
> Overall it looks good to me. there is a small blocker.
> 
> Also:
> 
> nit: highlighting some trial isn't that distinctive. I scrolled over a row and was expecting to find the trial highlighted but it wasn't easy to tell and that could confuse users?. with some colors, it works great. here one is highlighted:
> ![Screen Capture_select-area_20210108164949](https://user-images.githubusercontent.com/12127420/104078318-46ef4500-51d2-11eb-9b43-e241238f5f93.png)
> 
I've reduced the unfocused alpha by a little bit to make the focused on stand out more.

> ![Screen Capture_select-area_20210108165456](https://user-images.githubusercontent.com/12127420/104078314-435bbe00-51d2-11eb-9a11-75e284c0ca30.png)
> 
> suggestion: Hyperparameter visua..
> @ahj-determined any wording suggestions here? or maybe we link to the searcher section http://localhost:8080/docs/reference/experiment-config.html#searcher
> 
> this looks like a good place to advertise for hp search

I've updated to the copy @ahj-determined provided, thanks!

2021-01-11 17:28 UTC, hkang1 commented
> not directly related:
> ![Screen Capture_select-area_20210108170416](https://user-images.githubusercontent.com/12127420/104078566-ae59c480-51d3-11eb-92b7-c00718f376bb.png)

oops, fixed it this time. (incorrect scss module scope)

2021-01-11 17:41 UTC, hkang1 commented
> a bunch of nits
> 
> * highlighting (from plot to row) only happens on dots
>
The series lines unfortunately are not interactive. I think this is reasonable considering this is a canvas based chart and building in line proximity detection can be expensive for a performance based chart that can have tens of thousands of lines.

> * jagged line, blurry. can we up the resolution? is uplot canvas based?
>   250%
>   ![Screen Capture_select-area_20210108170918](https://user-images.githubusercontent.com/12127420/104078689-435cbd80-51d4-11eb-95a8-1a2264ebbd40.png)
>   
I couldn't find an option for uplot for this. There is a devicePixelRatio for HTML canvases but that's not a knob for us to change so far as I know... Let me know if you find some options regarding this.d

>   * maybe an option would be move the axis labels out of the chart later if we want it to match the rest of the page easier.
>     100%
>     ![Screen Capture_select-area_20210108170653](https://user-images.githubusercontent.com/12127420/104078653-18726980-51d4-11eb-826a-4c5e907bf089.png)
>
This is certainly an option but I don't think it gets us much considering the overhead of managing the labels ourselves. Having uPlot manage allows it to dynamically figured out the layout in relation to the chart and axes labels. For styling the labels to match the page, we can actually use fonts, but I haven't looked too much into this yet...

> * zoom between the data points and you don't see any lines. this is understandable but could it be confusing?
>
I don't think it's supposed to lose the lines when you zoom in. Can't seem to replicate this behavior, maybe I am misunderstanding.

2021-01-13 18:34 UTC, hamidzr approved these changes
LGTM. minus the waiting messaging on terminal states https://github.com/determined-ai/determined/pull/1753#issuecomment-758103912

thanks @hkang1

2021-01-13 21:43 UTC, hkang1 commented
> LGTM. minus the waiting messaging on terminal states [#1753 (comment)](https://github.com/determined-ai/determined/pull/1753#issuecomment-758103912)
> 
> thanks @hkang1

terminal experiment messaging added, thanks for the quick review @hamidzr !

2021-01-13 21:45 UTC, merged