docs: add DGX instructions for determined-deploy
determined-ai/determined pull request #1955
Opened 2021-02-11 03:31 UTC by hoanghphan

## Description

## Test Plan

## Commentary (optional)

## Checklist

- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
See [Release Note](../docs/release-notes/README.md) for details.

2021-02-11 21:06 UTC, neilconway requested changes

2021-02-11 23:12 UTC, hoanghphan commented on docs/how-to/installation/deploy.txt
> +.. note::
That makes sense. I combined that to just be a note reminding users Docker is required for det-deploy local and linking to our existing Docker installation instructions.

2021-02-11 23:13 UTC, hoanghphan commented on docs/how-to/installation/deploy.txt
> +    sudo apt install python3-testresources
This caused an issue during the install but I haven't been able to reproduce it on a similar re-test so removing that part. Also removed installing pip as that should be expected given the instructions below.

2021-02-12 15:42 UTC, neilconway approved these changes

2021-02-12 19:09 UTC, merged