feat: supervised and unsupervised contrastive learning example
determined-ai/determined pull request #2157
Opened 2021-04-01 08:10 UTC by liamcli

## Description

## Test Plan

## Commentary (optional)

## Checklist

- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
See [Release Note](../docs/release-notes/README.md) for details.
- [ ] Licenses should be included for new code which was copied and/or modified from any external code.

2021-05-04 08:44 UTC, katport commented on examples/computer_vision/contrastive_learning_pytorch/train_eval_model_def.py
> +        self.cls_loss = torch.nn.CrossEntropyLoss().cuda()
self.context.to_device?

2021-05-04 08:44 UTC, katport commented on examples/computer_vision/contrastive_learning_pytorch/README.md
> +* [**model_def.py**](train_eval_model_def.py): alternate implementation of our PyTorchTrial interface that interleaves training the embedding and classifier heads in each train step.
the names here are a bit confusing, can we clarify these a bit?

2021-05-04 08:44 UTC, katport commented on examples/computer_vision/contrastive_learning_pytorch/train_eval_model_def.py
> +        self.train_cls_dataloader = self.build_train_cls_data_loader().get_data_loader(
can you elaborate more on why this step needs to happen?

2021-05-04 08:44 UTC, katport commented on examples/computer_vision/contrastive_learning_pytorch/train_eval_model_def.py
> +                    labels = labels.cuda()
self.context.to_Device

2021-05-04 08:44 UTC, katport commented on examples/computer_vision/contrastive_learning_pytorch/train_eval_model_def.py
> +                for i, batch in enumerate(self.train_cls_dataloader):
I'm not a huge fan of the second dataloader, is there a better way to do this?

2021-05-04 08:44 UTC, katport commented on examples/computer_vision/contrastive_learning_pytorch/train_eval_model_def.py
> +        assert (
This seems to be the exact same code as build_train_data_loader. Lets reuse code instead of having it duplicated.

2022-07-23 00:25 UTC, gh-determined-ai requested changes

2022-07-23 00:25 UTC, gh-determined-ai commented on docs/release-notes/2157-contrastive-learning.txt
> +   [SIMCLR](https://arxiv.org/abs/2002.05709) and [supervised
This isn't reStructuredText notation for links. They should be something like:
-  \`SIMCLR \<https://arxiv.org/abs/2002.05709>`_
-  \`supervised contrastive learning \<https://arxiv.org/abs/2004.11362>`_

2022-12-23 00:37 UTC, liamcli commented
closing due to low priority.  look into supporting [vissl](https://github.com/facebookresearch/vissl) in the future.

2022-12-23 00:37 UTC, closed without merging