Jq write docs
determined-ai/determined pull request #3706
Opened 2022-03-08 06:07 UTC by eecsliu

## Description
Add documentation for the full job queue.

## Test Plan

## Commentary (optional)

## Checklist

- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
See [Release Note](../docs/release-notes/README.md) for details.
- [ ] Licenses should be included for new code which was copied and/or modified from any external code.

2022-03-22 17:47 UTC, hamidzr approved these changes
thanks for updating the docs. I had 2 comments but otherwise lgtm

2022-03-22 17:47 UTC, hamidzr commented on docs/features/job-queue.txt
> +seen in the experiments section should appear. A job that has already started to run will not be
clarify that this is only the case if the job supports reporting progress. (so the users don't expect this for other job types)

2022-03-22 17:47 UTC, hamidzr commented on docs/features/job-queue.txt
> +For more information about the CLI options, see the CLI documentation or use ``det job list -h``.
👍🏼 I was just about to ask for this.

2022-03-22 17:47 UTC, hamidzr commented on docs/features/job-queue.txt
> +Both the WebUI and the CLI will display a table of results, ordered by scheduling order. Note that
something like
.. by the scheduling order _if available_ (eg supported by the scheduler type)

2022-03-22 17:52 UTC, gh-determined-ai requested changes
See https://hpe-my.sharepoint.com/:w:/p/gene_hartsell/EaLrSVnLWH9DvqmI8gMzuagB2iNwemRC7GPMlmppGpXoiQ?e=ntvZbz

2022-03-22 21:00 UTC, hamidzr commented
> https://hpe-my.sharepoint.com/:w:/p/gene_hartsell/EaLrSVnLWH9DvqmI8gMzuagB2iNwemRC7GPMlmppGpXoiQ?e=ntvZbz

I'm helping @eecsliu to wrap this up. I'm not sure what the ideal approach is to address the comments you had on the shared doc. I'm thinking I'll go through and apply the comments and introduce my own changes. then you can take another look after?

2022-03-22 21:01 UTC, hamidzr commented
note: we need to take out k8 mentions in the queue modification section

2022-03-22 21:24 UTC, gh-determined-ai commented
@hamidzr  The "official" right approach is here: https://determinedai.atlassian.net/wiki/spaces/DOC/pages/1101594663. But nobody's successfully followed that yet. Do what you can or want to with my comments and I'll follow with a quick review. All of the content needs to eventually get this treatment so you can either do it now or it will be taken care of along with everything else, later. Thanks.

2022-03-22 23:07 UTC, hamidzr commented on docs/features/job-queue.txt
> +seen in the experiments section should appear. A job that has already started to run will not be
I addressed this in my patch

2022-03-22 23:07 UTC, hamidzr commented
I molded the document back to rst format so we're closer to something releasable. I need to see what changed but I don't seem to get html output from `make -C docs build` to check out the final output. 

[jqwrite-docs.patch.txt](https://github.com/determined-ai/determined/files/8328356/jqwrite-docs.patch.txt)

2022-03-23 00:21 UTC, gh-determined-ai approved these changes

2022-03-23 00:21 UTC, gh-determined-ai commented on docs/features/job-queue.txt
> +does not represent the job priority. In addition to job order, the table incudes the job states and
Spelling: "incudes"

2022-03-23 00:21 UTC, gh-determined-ai commented on docs/features/job-queue.txt
> +#. Make the change you want on the pop up page, and click **OK**.
hyphenate: "pop-up"

2022-03-23 00:21 UTC, gh-determined-ai commented on docs/features/job-queue.txt
> +Using the job queue to modify jobs has a number of constraints:
I think "There are a number of constraints associated with using the job queue to modify jobs:" might sound a little better.

2022-03-23 00:21 UTC, gh-determined-ai commented on docs/features/job-queue.txt
> +The job queue can be changed in the WebUI **Job Queue** Section or by using the CLI ``det job
"... Section ..." should be lowercase: "... section ..."

2022-03-23 00:50 UTC, merged