docs: add release notes for 0.19.2
determined-ai/determined pull request #4877
Opened 2022-08-25 23:26 UTC by mackrorysd

Add release notes for 0.19.2.

2022-08-26 16:55 UTC, sirredbeard commented on docs/release-notes.rst
> +-  Kubernetes: Fixed an issue where restoring a job in into a Kubernetes set up could crash the
nit: `in into` is repetitive

2022-08-29 14:10 UTC, vishnu2kmohan requested changes
Minor tweaks to the release notes announcing the Slurm integration for EE.

2022-08-29 14:10 UTC, vishnu2kmohan commented on docs/release-notes.rst
> +-  Cluster: Determined Enterprise Edition can now be deployed on a Slurm cluster. When using Slurm,
```suggestion
-  Cluster: The enterprise edition of Determined ([HPE Machine Learning Development Environment](https://www.hpe.com/us/en/solutions/artificial-intelligence/machine-learning-development-environment.html)), can now be deployed on a Slurm cluster. When using Slurm,
```

2022-08-29 14:10 UTC, vishnu2kmohan commented on docs/release-notes.rst
> +   integration enables existing Slurm workloads and Determined workloads to coexist and Determined
```suggestion
   integration enables existing Slurm workloads and Determined workloads to coexist and ```

2022-08-29 14:10 UTC, vishnu2kmohan commented on docs/release-notes.rst
> +   workloads to access all of the advanced capabilities of the Slurm workload manager. The
```suggestion
   access all of the advanced capabilities of the Slurm workload manager. The
```

2022-08-29 14:10 UTC, vishnu2kmohan commented on docs/release-notes.rst
> +   Determined Slurm integration can use either Singularity or PodMan for the container runtime.
```suggestion
   Determined Slurm integration can use either Singularity or Podman for the container runtime.
```

2022-08-29 16:06 UTC, vishnu2kmohan approved these changes
Thanks, @mackrorysd!

2022-08-29 19:54 UTC, mackrorysd commented
Merging despite the CI failures: test-e2e is failing because of a Docker Hub outage only (and the docs don't affect these tests). Linting is failing because of an API change already in master (so the compatibility check doesn't apply) and because of a genuine Python Linting issue that was fixed after branching which I won't cherry-pick at this point.

2022-08-29 19:54 UTC, merged