chore: inherit PBS & Slurm defaults
determined-ai/determined pull request #5560
Opened 2022-12-07 23:02 UTC by phillip-gaisford

## Description

## Test Plan

## Commentary (optional)

## Checklist

- [ ] Changes have been manually QA'd
- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
  See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-notes/README.md) for details.
- [ ] Licenses should be included for new code which was copied and/or modified from any external code.

2022-12-08 16:38 UTC, jerryharrow reviewed
lgtm, but should get Bradley's approval.

2022-12-09 14:55 UTC, stoksc approved these changes
lgtm

2022-12-09 14:55 UTC, stoksc commented on master/internal/api_command.go
> +		a.m.config.TaskContainerDefaults,
maybe ideally this wouldn't get passed, but i guess i need to think about the abstractions some more

2022-12-09 14:58 UTC, stoksc requested changes

2022-12-09 14:58 UTC, stoksc commented on master/internal/rm/agentrm/agent_resource_manager.go
> +	return response.(model.TaskContainerDefaultsConfig)
oh oops, this should use a.Ask

2022-12-09 14:59 UTC, stoksc commented on master/internal/rm/agentrm/agent_resource_manager.go
> +	return response.(model.TaskContainerDefaultsConfig)
same in the dispatcher ee code. if you peruse the code for https://github.com/determined-ai/determined/blob/master/master/internal/rm/actorrm/actor_resource_manager.go#L265-L291 it should sort of explain why (what it handles that this doesn't)

2022-12-09 16:55 UTC, stoksc commented on master/internal/rm/agentrm/agent_resource_manager.go
> +}
```suggestion
) (result model.TaskContainerDefaultsConfig, err error) {
        req := taskContainerDefaults{fallbackDefault: fallbackConfig, resourcePool: pool}
	return result, a.Ask(ctx, req, &result)
}
```

2022-12-09 16:56 UTC, stoksc approved these changes
lgtm

2022-12-09 18:14 UTC, merged