chore: remove storybook leftover
determined-ai/determined pull request #6426
Opened 2023-03-31 22:57 UTC by keita-determined

## Description
There's some leftover of storybook. 
related: #5576

## Test Plan
- Check if nothing harmful to remove

## Commentary (optional)

## Checklist

- [ ] Changes have been manually QA'd
- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
  See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-notes/README.md) for details.
- [ ] Licenses should be included for new code which was copied and/or modified from any external code.

## Ticket

2023-03-31 23:01 UTC, keita-determined commented on webui/react/src/storybook/utils.ts
> -export const enumToOptions = <T>(enm: Record<string, string | number>): Record<string, T> => {
this file is not used anymore

2023-03-31 23:01 UTC, keita-determined commented on webui/react/src/tests/shared/generateTestData.ts
renamed since `storybook` is not the right name

2023-04-03 17:53 UTC, EmilyBonar requested changes
Just a couple of tweaks

2023-04-03 17:53 UTC, EmilyBonar commented on webui/react/src/test_utils/generateTestData.ts
fix: since we're moving it anyway, this should probably become something like `utils/test.ts` instead of creating a new `test_utils` folder.

2023-04-03 17:53 UTC, EmilyBonar commented on webui/react/.gitignore
> -build-storybook/
nit: I think this should probably stay in the gitignore so that no one accidentally commits an old build-storybook folder

2023-04-03 18:09 UTC, keita-determined commented on webui/react/src/test_utils/generateTestData.ts
`generateTestData.ts` is under `utils/tests` folder now

2023-04-03 18:10 UTC, EmilyBonar approved these changes

2023-04-03 18:15 UTC, EmilyBonar commented on webui/react/src/test_utils/generateTestData.ts
That works. We should check if there are other utils that we only use in tests and put them in there too, but that can be a different PR

2023-04-03 18:19 UTC, keita-determined commented on webui/react/src/test_utils/generateTestData.ts
i think this should be a different PR too. could you make a ticket?

2023-04-03 18:19 UTC, merged