feat: add bulk actions to glide table [WEB-981]
determined-ai/determined pull request #6493
Opened 2023-04-06 21:04 UTC by EmilyBonar

## Description
![Screenshot 2023-04-06 at 16-58-32 Uncategorized Experiments - Determined](https://user-images.githubusercontent.com/15078396/230492654-0ed302cb-e6bd-49aa-8bb7-c6f0645c7459.png)

Note: The bulk delete api is currently a no-op on the backend, that functionality will be implemented separately.

## Test Plan

- Edit button becomes visible when rows are selected and vanishes when they aren't
- Count on Edit button reflects number of rows selected (including "All") if all are selected
- Bulk actions trigger correctly when specific experiments are selected and when all experiments in the list are selected 

## Commentary (optional)

## Checklist

- [ ] Changes have been manually QA'd
- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
  See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-notes/README.md) for details.
- [ ] Licenses should be included for new code which was copied and/or modified from any external code.

## Ticket

2023-04-06 21:29 UTC, ashtonG commented on webui/react/src/pages/F_ExpList/F_ExperimentList.tsx
> +
consider expressing this subset of the `Action` type as its own type to use in `sendBatchAction` and `submitBatchAction`. That will indicate the `default` case of the switch statement in `sendBatchAction` as unreachable, meaning we shouldn't need to return an empty promise there.
```suggestion
] as const;

type BatchAction = typeof batchActions[number];
```

2023-04-06 21:40 UTC, keita-determined reviewed
suggestion: selected rows should be unselected after action

https://user-images.githubusercontent.com/109113616/230498590-af08fb12-c8ec-4a5e-aafb-3c0160ebc9b8.mov

---

`Select all` doesn't not work. Is it expected?

https://user-images.githubusercontent.com/109113616/230498787-de5387c6-7f9d-40b7-bfb9-572613e29e5d.mov

2023-04-07 14:00 UTC, ClaireNeveu requested changes
Referencing the [figma](https://www.figma.com/file/fI9wKqYd3HLflVCBjb3xOS/experiment-list?node-id=76-8266&t=pIzbOiYZGTZ7Dhtg-4), the new experiment listing has its own unicorn buttons. The dropdown portion also does not match the figma.

2023-04-07 14:26 UTC, ClaireNeveu approved these changes
Disregard my previous review, talked it over with Alex and we're gonna use the UI kit buttons.

2023-04-10 18:51 UTC, EmilyBonar commented on webui/react/src/hooks/useModal/Experiment/useModalExperimentMove.tsx
> +    const results = await moveExperiments({ destinationProjectId, experimentIds, filters });
My understanding is that if `filters !== undefined` then `experimentIds` is essentially ignored. Is that correct @mapmeld?

2023-04-10 19:00 UTC, EmilyBonar commented on webui/react/src/pages/F_ExpList/F_ExperimentList.tsx
> +        all the eligible selected experiments?
How would you suggest changing it to reflect that?

2023-04-10 19:33 UTC, mapmeld commented on webui/react/src/hooks/useModal/Experiment/useModalExperimentMove.tsx
> +    const results = await moveExperiments({ destinationProjectId, experimentIds, filters });
that's what I set up, though if this rule for filters is controversial, this would be a good time to evaluate

2023-04-10 20:36 UTC, trentwatt commented on webui/react/src/hooks/useModal/Experiment/useModalExperimentMove.tsx
> +    const results = await moveExperiments({ destinationProjectId, experimentIds, filters });
IMO `experimentIds` should be just another filter. But If this works as is, I think it's good for now

2023-04-10 20:41 UTC, trentwatt commented on webui/react/src/pages/F_ExpList/F_ExperimentList.tsx
> +        all the eligible selected experiments?
something like
```
Are you sure you want to ${action.toLocaleLowerCase()}
        all eligible ${
            selectAll ? 'experiments matching the current filters'
                            : 'selected experiments'
         }?
```
?

2023-04-12 15:45 UTC, alexjdetermined commented
* For select all, show "count" instead of "All" in button and bulk confirm modal. E.g. "Edit (1,432)" instead of "Edit (all)" and "Confirm action for 1,432 experiments" instead of "Confirm action for all experiments"
* Cancel from "Move" modal shouldn't de-select rows

2023-04-12 21:01 UTC, trentwatt commented on webui/react/src/pages/F_ExpList/glide-table/TableActionBar.tsx
> +            message: 'No eligable experiments',
```suggestion
            message: 'No eligible experiments',
```

2023-04-12 21:02 UTC, trentwatt commented on webui/react/src/pages/F_ExpList/F_ExperimentList.tsx
> +      const response = await getExperiments(
i think we want to still use the new API?

2023-04-12 21:03 UTC, trentwatt commented on webui/react/src/components/ExperimentMoveModal.tsx
> +              {numFailures} out of {numFailures + numSuccesses} eligable experiments failed to move
```suggestion
              {numFailures} out of {numFailures + numSuccesses} eligible experiments failed to move
```

2023-04-12 21:03 UTC, trentwatt commented on webui/react/src/components/ExperimentMoveModal.tsx
> +        message: 'No eligable experiments',
```suggestion
        description: 'No selected experiments were eligible for moving',
        message: 'No eligible experiments',
```

2023-04-13 23:18 UTC, trentwatt reviewed
looking good, couple of edge cases

- I got `row is undefined` when moving all experiments.

<img width="701" alt="image" src="https://user-images.githubusercontent.com/28383080/231899232-1133a409-9e4a-4b04-acad-02b446f30169.png">

changing line `234` of `GlideTable.tsx` to the below seems to resolve:
```
if (row && Loadable.isLoaded(row)) {
```


- Also i noticed that if i move all the experiments when I am scrolled down the number of experiments does not get updated properly:  


https://user-images.githubusercontent.com/28383080/231901197-81b7caa0-ea08-49aa-a952-29c2a6d13488.mov  

doing the following in `fetchExperiments` resolved that issue:

```
return [
          ...experimentBeforeCurrentPage,
          ...response.experiments.map((e) => Loaded(e.experiment)),
          ...experimentsAfterCurrentPage,
        ].slice(0, response.pagination.total!);
```
(i am pretty sure `response.pagination.total` will always be defined even though our types don't know that).

afterwards, i occasionally got `record is undefined`, but adding some null checks resolved:


```
      const selectedIds = selectedRowIndices
        .map((idx) => data?.[idx])
here >  .filter((row) => row !== undefined)
        .filter(Loadable.isLoaded)
```

2023-04-13 23:20 UTC, trentwatt commented
> For select all, show "count" instead of "All" in button and bulk confirm modal. E.g. "Edit (1,432)" instead of "Edit (all)" and "Confirm action for 1,432 experiments" instead of "Confirm action for all experiments"


we can also use `response.pagination.total` for that^^

2023-04-14 18:28 UTC, trentwatt approved these changes
Looks really slick, great work!

2023-04-14 18:33 UTC, merged