chore: refactor PermissionDenied RBAC errors [DET-8946]
determined-ai/determined pull request #6618
Opened 2023-04-24 14:35 UTC by carolinaecalderon

## Description
These changes modify the RBAC interfaces to return just `err`and let `PermissionDeniedError` through for the `CanGetNSC` and `CanGetTensorboard` functions. The `PermissionDeniedError` is checked in other functions to return detailed, relevant error messages.

## Test Plan

I tested the endpoints affected following the test plan from https://github.com/determined-ai/determined-ee/pull/823.

## Checklist

- [ ] Changes have been manually QA'd
- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
  See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-notes/README.md) for details.
- [ ] Licenses should be included for new code which was copied and/or modified from any external code.

## Ticket
DET-8946

2023-04-26 19:16 UTC, eecsliu reviewed
Looks good! I think it's fine to ship as is, but give the comments a glance. All except one are nits.

2023-04-27 16:44 UTC, carolinaecalderon commented
@eecsliu 
So I looked more into the new ticket this morning along the lines of https://hpe-aiatscale.atlassian.net/browse/DET-9400 & I have an idea for an intermediate step:
```
func ErrorMsg(err error, sub error, sub2 error) error {
	if err != nil {
		if _, ok := err.(PermissionDeniedError); ok {
			return sub
		}
		return err
	}
	return sub2
}
```
where sub & sub2 are simply the two error code substitutes for any given function
And then used as follows:
```
err = expauth.AuthZProvider.Get().CanGetExperiment(ctx, *user, e)
errVal := authz.ErrorMsg(err, echo.NewHTTPError(http.StatusNotFound, "service not found: "+taskID), nil)
return err != nil, errVal #or return errVal, or whatever the function actually returns
```
This takes the +220/-204 diff to +160/-228

2023-04-27 19:32 UTC, carolinaecalderon commented on master/internal/api_auth.go
> +				err = echo.NewHTTPError(http.StatusNotFound, "service not found: "+taskID)
Resolved w/ these new functions
```
// IsPermissionDenied checks if err is of type PermissionDeniedError
func IsPermissionDenied(err error) bool {
	if _, ok := err.(PermissionDeniedError); ok {
		return true
	}
	return false
}

// ConvertError substitutes an error if it is of type PermissionDeniedError
func ConvertError(err error, sub error) error {
	if IsPermissionDenied(err) {
		return sub
	}
	return err
}

```

2023-04-27 22:07 UTC, eecsliu approved these changes
Looks great! Nice work

![329693542_869592567627377_7940960205697930892_n](https://user-images.githubusercontent.com/31023784/235001721-d14592b6-28c4-492c-8b60-a39dc6267717.png)

2023-04-28 01:03 UTC, maxrussell requested changes
This looks fantastic! This permission logic is much easier to read—and therefore less likely to hide bugs!

I think I may have found a couple bugs, though. Would you mind checking whether those cases are covered by integration tests and if not, adding failing tests and then fixing?

2023-04-28 14:26 UTC, carolinaecalderon commented on master/internal/api_checkpoint.go
> +		return err
Done!

2023-04-28 14:28 UTC, carolinaecalderon commented on master/internal/api_project.go
> +		if authz.IsPermissionDenied(err) {
Oh right, should be `!authz.IsPermissionDenied(err)`

2023-04-28 14:29 UTC, carolinaecalderon commented on master/internal/api_tasks.go
> +		if authz.IsPermissionDenied(err) {
Done!

2023-04-28 14:34 UTC, carolinaecalderon commented on master/internal/trials/api_trials.go
> +		return nil, authz.ConvertError(fmt.Errorf("unable to create collection %w", err), status.Error(
Oh right -- bad substitution
Going to change with
```
err = AuthZProvider.Get().CanCreateTrialCollection(ctx, curUser, req.ProjectId)
	if authz.IsPermissionDenied(err) {
		return nil, status.Error(
			codes.PermissionDenied,
			"unable to create collection",
		)
	}
	if err != nil {
		return nil, fmt.Errorf("unable to create collection %w", err)
	}
```

2023-04-28 14:36 UTC, carolinaecalderon commented on master/internal/authz/permission_denied_error.go
> +func ConvertError(err error, sub error) error {
Done!

2023-05-04 00:06 UTC, maxrussell approved these changes

2023-05-04 16:14 UTC, merged