feat: add theme (fonts, colors, etc) to design kit
determined-ai/determined pull request #6847
Opened 2023-05-16 18:09 UTC by thiagodallacqua-hpe

## Description

Ticket: WEB-817

The idea is to collect all information about the current theme structure into our design kit.

## Test Plan

go to the `/design` route, the theme info should be present.

![Screen Shot 2023-05-18 at 15 44 48](https://github.com/determined-ai/determined/assets/104855841/fc7ec098-c2d0-4c1f-ad16-d2d05525f1d6)

![Screen Shot 2023-05-23 at 11 36 51](https://github.com/determined-ai/determined/assets/104855841/f146495f-96c6-4461-af96-c1e8c91a442e)
![Screen Shot 2023-05-23 at 11 36 46](https://github.com/determined-ai/determined/assets/104855841/44b55f9d-1b6b-4343-830f-79e73b1663ba)
![Screen Shot 2023-05-23 at 11 36 37](https://github.com/determined-ai/determined/assets/104855841/7d19704e-362d-4eb5-8e7a-2f48e70f1963)
![Screen Shot 2023-05-23 at 11 36 29](https://github.com/determined-ai/determined/assets/104855841/3bc8bb5b-5675-4e93-8f56-14772741ec9e)

## Commentary (optional)

With the latest implementation, the `Header` and the `Paragraph` components has new props:

```typescript
// at src/utils/fonts.ts
export const TypographySize = {
  default: 'default',
  L: 'L',
  S: 'S',
  XL: 'XL',
  XS: 'XS',
} as const;

// Header

interface Props {
  size?: TypographySize;
}

// Paragraph

interface Props {
  size?: TypographySize;
  type?: 'single line' | 'multi line';
  font?: 'code' | 'ui';
}
```

Each `size` has it's own `font-size` and `line-height` following design spec (check the screenshots above).

For the `Paragraph` there's a `type` prop, which differentiates the single line from the multi-line paragraphs, and the `font` prop which differentiates regular UI text to code text.

## Checklist

- [ ] Changes have been manually QA'd
- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
  See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-notes/README.md) for details.
- [ ] Licenses should be included for new code which was copied and/or modified from any external code.

## Ticket

2023-05-17 14:18 UTC, ClaireNeveu requested changes

2023-05-17 14:18 UTC, ClaireNeveu commented on webui/react/src/pages/DesignKit.tsx
> +const themeStatus = [
These shouldn't be defined in the demo page, they should be accessible to the rest of the design kit as enumerations.

2023-05-17 14:18 UTC, ClaireNeveu commented on webui/react/src/pages/DesignKit.tsx
> +        <p>Here are a quick demo of the current theme (colors, fonts, etc)</p>
"A variety of colors are available for use with the components in the UI Kit."

2023-05-17 18:47 UTC, ClaireNeveu requested changes
I don't see an enum for the font sizes?

2023-05-17 18:47 UTC, ClaireNeveu commented on webui/react/src/utils/themes.ts
> +export enum Status {
We've standardized on using "object as const" for enums, please bring this in-line.

2023-05-17 18:47 UTC, ClaireNeveu commented on webui/react/src/utils/themes.ts
> +export enum Fonts {
Enums should always be singular.

2023-05-17 18:47 UTC, ClaireNeveu commented on webui/react/src/utils/themes.ts
> +export enum Backgrounds {
Please put the colors in a `color` file and the fonts in a `font` file.

2023-05-17 18:49 UTC, ClaireNeveu commented on webui/react/src/pages/DesignKit.tsx
> +              <h4 style={{ marginBottom: '20px' }}>Header</h4>
We should be using the existing `Header` component.

2023-05-18 14:02 UTC, ClaireNeveu requested changes

2023-05-18 14:02 UTC, ClaireNeveu commented on webui/react/src/components/kit/Typography/Header.tsx
> +  className?: string;
UI Kit components should not take arbitrary classes or styles.

2023-05-18 14:02 UTC, ClaireNeveu commented on webui/react/src/components/kit/Typography/Paragraph.tsx
> +interface Props {
As above so here

2023-05-18 14:02 UTC, ClaireNeveu commented on webui/react/src/utils/fonts.ts
> +};
You need an `as const` on these so they infer correctly, you should also export a matching type. See other cases where we use enums as an example.

2023-05-18 15:09 UTC, ClaireNeveu commented on webui/react/src/utils/fonts.ts
> +export const Header = {
Are these actually used? It looks like you defined a separate enum in the components themselves.

2023-05-18 16:23 UTC, ClaireNeveu commented on webui/react/src/utils/fonts.ts
> +export const Header = {
Where would we use these other than the header? And if line height is something we want then why _doesn't_ header take them? (not clear to me that we do want that, was it a request from design?)

2023-05-18 16:31 UTC, ClaireNeveu commented on webui/react/src/utils/fonts.ts
> +export const Header = {
In that case what you have here doesn't accomplish what Alex asked for because it's not actually usable.

2023-05-18 16:41 UTC, ClaireNeveu commented on webui/react/src/utils/fonts.ts
> +export const Header = {
By CSS variables do you mean the `ParagraphSizes` you defined?

2023-05-18 16:45 UTC, hkang1 commented
**suggestion:**
- for the design kit layout of colors, can we put them in a `<Grid>` or something to make them more compact 🙏 ? They take up quite a bit of vertical space and there's a lot of space to the right on a typical browser size window.
- add a contrasting border to all the color boxes so even colors that are similar to the background it sits on will be visible

2023-05-18 17:16 UTC, ClaireNeveu commented on webui/react/src/utils/fonts.ts
> +export const Header = {
How do you use that with `Paragraph` or `Header`?

2023-05-18 17:25 UTC, ClaireNeveu commented on webui/react/src/utils/fonts.ts
> +export const Header = {
I can read the code. You just said that the enums in the ts code aren't the same as the css vars.

2023-05-18 18:22 UTC, ClaireNeveu commented on webui/react/src/utils/themes.ts
> +import { ValueOf } from 'shared/types';
File should be color, not theme.

2023-05-18 18:23 UTC, ClaireNeveu commented on webui/react/src/utils/fonts.ts
> +export const TypographySizes = {
Should be singular.

2023-05-18 18:24 UTC, ClaireNeveu commented on webui/react/src/pages/DesignKit.tsx
> +      <AntDCard title="Fonts">
These should be under `Typography`.

2023-05-18 18:24 UTC, ClaireNeveu commented on webui/react/src/pages/DesignKit.tsx
> +    <ComponentSection id="Theme" title="Theme">
Section should be `Color`.

2023-05-18 18:55 UTC, ClaireNeveu approved these changes
Check with @alexjdetermined That the actual colors/styles are correct. Looks good on my end.

2023-05-19 16:13 UTC, hkang1 approved these changes
Great work! Minor suggestions but nothing blocking.

2023-05-23 15:24 UTC, alexjdetermined commented
1. --theme-status-inactive-weak/strong is flipped in order compared to the others.
2. Change border color around color blocks from "--theme-stage-on" to "--theme-surface-border"

2023-05-23 17:21 UTC, alexjdetermined approved these changes
LGTM!

2023-05-23 17:22 UTC, merged