feat: switch from Monaco to CodeMirror
determined-ai/determined pull request #6926
Opened 2023-05-22 19:32 UTC by thiagodallacqua-hpe

## Description

Ticket: WEB-1241

The Monaco editor that we have been using, although is a great tool, it is very heavy in size... The proposal here is to replace it with CodeMirror (using the react wrapper).

## Test Plan

Check if the functionality of all instances of where we used Monaco still works:

- Code tab (under experiments)
- modal view filters
- experiment create modal
- jupyter lab modal
- experiment configuration
- markdown 
- workspace create modal

![Screen Shot 2023-05-22 at 16 25 38](https://github.com/determined-ai/determined/assets/104855841/91372882-18ba-4901-87d7-1310e4bf9395)
![Screen Shot 2023-05-22 at 16 25 24](https://github.com/determined-ai/determined/assets/104855841/458f9ea9-dfc6-49ef-8ec2-d14dfb721e9d)
![Screen Shot 2023-05-22 at 16 25 16](https://github.com/determined-ai/determined/assets/104855841/f055908d-20a8-44dd-815a-8fb39c0e7566)
![Screen Shot 2023-05-22 at 16 25 07](https://github.com/determined-ai/determined/assets/104855841/28d14fb8-991f-4577-895f-cd07ab73ea7c)
![Screen Shot 2023-05-24 at 15 36 19](https://github.com/determined-ai/determined/assets/104855841/ff482b0d-a9e0-4295-a7b5-46082b6f8675)
![Screen Shot 2023-05-24 at 15 34 47](https://github.com/determined-ai/determined/assets/104855841/959bcf94-7a0f-4361-a8d7-676e92347f3c)

## Commentary (optional)

## Checklist

- [ ] Changes have been manually QA'd
- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
  See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-notes/README.md) for details.
- [ ] Licenses should be included for new code which was copied and/or modified from any external code.

## Ticket

2023-05-24 18:32 UTC, mapmeld commented on webui/react/src/components/kit/CodeEditor.tsx
> +          readOnly
should be `readOnly={readonly}`

2023-05-24 18:36 UTC, mapmeld commented on webui/react/src/components/WorkspaceCreateModal.tsx
> -                      readOnly: !canModifyCPS,
there are a few places like this where the old editor had `readOnly` and should be passed to `CodeMirrorEditor`

2023-05-25 15:47 UTC, ashtonG requested changes
noticed we're only seeing .4MB in savings on the vendor bundle with this PR -- given the tests in the ERD, it should be more. Looking at the bundle analysis, it seems like the `@uiw/codemirror-extensions-langs` package is importing every language package. We should only import the languages we need.

2023-05-25 20:44 UTC, johnkim-det commented
> > is there a reason why `CodeEditor` is in the UI kit and imports `CodeMirrorEditor`, but the app uses `CodeMirrorEditor` instead of `CodeEditor`?
> > ideally the UI kit component would not import any components outside of the UI kit, and the app would use the UI kit component.
> 
> AFAIK, `CodeEditor`, so far, is the component for the `Code` tab 🤔, but, I guess we could open a ticket for replacing that into the UI kit

Oh I see, didn't realize the difference between the two, but that makes sense. I suppose a ticket for adding `CodeMirrorEditor` to the UI kit at some point could be good.

Until that change happens, will still probably want to make a copy of `CodeMirrorEditor` within the `kit` folder, per https://hpe-aiatscale.atlassian.net/browse/WEB-1243. But I can just do that in my PR if you merge this one first.

2023-05-25 20:55 UTC, ashtonG requested changes
We are still importing every language module, This time via `@codemirror/language-data`. Do we need it for code highlighting in markdown?

2023-05-26 17:05 UTC, ashtonG approved these changes
<img width="612" alt="image" src="https://github.com/determined-ai/determined/assets/701438/b2155808-1ea8-429d-9c97-655f7a40465a">
let's goooooo

2023-05-26 17:09 UTC, merged