fix: deepspeed autotune user guide clarification
determined-ai/determined pull request #7140
Opened 2023-06-14 14:13 UTC by garrett361

## Description

Simplifies the `DeepSpeedTrial` section of the user guide and also adds a warning about pipeline and model parallelism.

## Test Plan

## Commentary (optional)

## Checklist

- [ ] Changes have been manually QA'd
- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
  See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-notes/README.md) for details.
- [ ] Licenses should be included for new code which was copied and/or modified from any external code.

## Ticket

2023-06-14 15:46 UTC, ighodgao approved these changes
Much clearer! Thank you

2023-06-14 16:33 UTC, tayritenour requested changes
@tara-det-ai should look at this

2023-06-14 16:40 UTC, garrett361 commented on docs/model-dev-guide/apis-howto/deepspeed/autotuning.rst
> +   This is a warning
Done, oops.

2023-06-14 16:40 UTC, garrett361 commented
> @tara-det-ai should look at this

Yep, I think

2023-06-14 17:18 UTC, tara-det-ai commented on docs/model-dev-guide/apis-howto/deepspeed/autotuning.rst
> +
.. note::

This feature is not compatible with pipeline or model parallelism. The model to be trained must be a ``DeepSpeedEngine`` instance and not a ``PipelineEngine`` instance.

2023-06-14 17:23 UTC, tara-det-ai commented on docs/model-dev-guide/apis-howto/deepspeed/autotuning.rst
> +In order to use Determined's DeepSpeed Autotune with ``DeepSpeedTrial`` there are two requirements.
avoid references to specific counts. simplify "In order to" with "To".

To use Determine's DeepSpeed Autotune with ``DeepSpeedTrial``, you must meet the following requirements.

2023-06-14 17:30 UTC, tara-det-ai reviewed
requested changes

2023-06-14 18:13 UTC, tara-det-ai approved these changes
LGTM

2023-06-20 17:58 UTC, tayritenour approved these changes
LGTM

2023-06-20 17:59 UTC, merged