feat: Add the InlineForm component
determined-ai/determined pull request #7199
Opened 2023-06-23 20:42 UTC by thiagodallacqua-hpe

## Description

Ticket: WEB-1348

Adding the `InlineForm` component to the UI kit.

## Test Plan

- Go to the `/design` page
- test the elements in the `InlineForm` section

![Screen Shot 2023-07-07 at 15 59 19](https://github.com/determined-ai/determined/assets/104855841/fdc921b6-473d-44e4-b6a0-7f8f1d6ad6f5)
![Screen Shot 2023-07-07 at 15 59 07](https://github.com/determined-ai/determined/assets/104855841/e02117b0-ac24-45f3-9e5e-31c1dbcf88b0)

## Commentary (optional)

## Checklist

- [ ] Changes have been manually QA'd
- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
  See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-notes/README.md) for details.
- [ ] Licenses should be included for new code which was copied and/or modified from any external code.

## Ticket

2023-06-27 20:28 UTC, johnkim-det reviewed
Can you use this component in `SettingsAccount` and make sure that existing code is consistent with what you wrote here?

2023-06-28 13:27 UTC, ClaireNeveu requested changes
The spacing is nowhere near what's in the wireframe

2023-06-28 13:28 UTC, ClaireNeveu commented on webui/react/src/components/kit/InlineForm.tsx
> +  type: 'input' | 'select';
This should take any valid form component, not a string.

2023-06-29 18:30 UTC, johnkim-det commented
sorry if it wasn't clear, can you actually change `SettingsAccount` to use the new component?

2023-06-29 19:05 UTC, ClaireNeveu requested changes

2023-06-29 19:05 UTC, ClaireNeveu commented on webui/react/src/components/kit/InlineForm.tsx
> +  forceEdit = false,
What is this argument for?

2023-06-29 19:05 UTC, ClaireNeveu commented on webui/react/src/components/kit/InlineForm.tsx
> +  inputValue = '',
This should just be `initialValue`.

2023-06-29 19:05 UTC, ClaireNeveu commented on webui/react/src/components/kit/InlineForm.tsx
> +  inputValue = '',
Also it would be great if you didn't conflate initialValue and `value` and allowed the component to be uncontrolled.

2023-06-29 19:05 UTC, ClaireNeveu commented on webui/react/src/components/kit/InlineForm.tsx
> +  inputValue?: string | number;
Value can be anything the input accepts/emits which is more than string and number.

2023-06-29 19:05 UTC, ClaireNeveu commented on webui/react/src/components/kit/InlineForm.tsx
> +  const submitForm = useCallback(() => {
You're never actually calling form submit so validators won't run.

2023-07-05 13:36 UTC, ClaireNeveu commented on webui/react/src/components/kit/InlineForm.tsx
> +  inputValue = '',
`initialValue` and `value` have different uses. You should preserve the API that a user would get from using `Form` and `Form.Item` together. As far as I can see you just changed the component from only allowing controlled to now only allowing uncontrolled.

2023-07-05 13:39 UTC, ClaireNeveu commented on webui/react/src/components/kit/InlineForm.tsx
> +            <Form.Item>
These buttons aren't form items.

2023-07-05 13:40 UTC, ClaireNeveu commented on webui/react/src/components/kit/InlineForm.tsx
> +            <Form.Item>
Is this just for CSS purposes? I notice you aren't passing any props.

2023-07-05 15:29 UTC, johnkim-det commented
Just wanted to also call out as a comment here that ideally this PR could include using `InlineForm` within `InputShortcut`

2023-07-05 15:31 UTC, ClaireNeveu commented on webui/react/src/components/kit/InlineForm.tsx
> +  forceEdit = false,
I think we always want it to start in the closed state.

2023-07-05 16:19 UTC, ClaireNeveu commented on webui/react/src/components/kit/InlineForm.tsx
> +            <Form.Item>
Form.Item should only be used for the form values.

2023-07-05 17:09 UTC, ClaireNeveu commented
@thiagodallacqua-hpe It's not an adaptation, `InlineForm` needs to work for _all_ inputs, just like `Form`.

2023-07-07 15:11 UTC, ClaireNeveu requested changes

2023-07-07 15:11 UTC, ClaireNeveu commented on webui/react/src/components/kit/InlineForm.tsx
> +  displayValue = '',
Reiterating here for posterity that this needs to support being a controlled component or an uncontrolled component just like any other input. Right now it's a weird mix of both.

2023-07-07 16:01 UTC, ClaireNeveu commented on webui/react/src/components/kit/InlineForm.tsx
> +  displayValue?: Primitive;
You should use a generic type, not `any`.

2023-07-07 18:19 UTC, ClaireNeveu requested changes

2023-07-07 18:19 UTC, ClaireNeveu commented on webui/react/src/pages/DesignKit.tsx
> +          <InlineForm<string>
Please split this into controlled and uncontrolled examples. Controlled examples should set `value` and `onSubmit` with a `useState` and uncontrolled should just set `initialValue` and then do nothing in the `onSubmit`.

2023-07-07 19:28 UTC, ClaireNeveu requested changes
This looks really good, just one final change: When form validation fails you should not be able to submit the form.

2023-07-07 19:45 UTC, ClaireNeveu requested changes
If the form fails validation and then you press the checkmark button again it creates an anomalous space under the error message.

If you trigger a validation error and then close the form, the error message remains. Closing the form without submitting should reset it.

2023-07-10 16:50 UTC, ClaireNeveu requested changes
If I have a text input with a validator and I delete the value then exit out of the form, when I re-open the form the value remains deleted. The form should reset when cancelled out of.

1. On "Input with validator" set a value of "test" and hit submit
2. Open it again and clear the value, see error
3. Close with cancel button
4. Re-open, should see "test" but instead field is blank.

2023-07-10 18:13 UTC, johnkim-det approved these changes

2023-07-10 18:26 UTC, merged