feat: add tooltip linebreak to the project card
determined-ai/determined pull request #7995
Opened 2023-09-26 18:45 UTC by thiagodallacqua-hpe

## Description

Ticket: WEB-1045

## Test Plan
- Go to the dashboard
- hover over a card, at the "TimeAgo" component.
- the time should be formated as: 

```
Last experiment started on: <br> 
<date>
```

![Screen Shot 2023-09-26 at 15 43 05](https://github.com/determined-ai/determined/assets/104855841/468952a5-c047-4603-bc5e-5a65c215ba5a)

## Commentary (optional)

## Checklist

- [ ] Changes have been manually QA'd
- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
  See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-notes/README.md) for details.
- [ ] Licenses should be included for new code which was copied and/or modified from any external code.

## Ticket

2023-09-26 19:14 UTC, alexjdetermined approved these changes
LGTM

2023-09-26 19:15 UTC, keita-determined requested changes

2023-09-26 19:15 UTC, keita-determined commented on webui/react/src/components/TimeAgo.tsx
> +    const check = 'Last experiment started';
what if `tooltipFormat` includes other word? this should be more generic

2023-09-27 23:55 UTC, keita-determined commented on webui/react/src/components/TimeAgo.tsx
> +      .split(/\w{3,} \d{1,2}, \d{2,4}( - \d{1,2}:\d{1,2}( \w{2}|\s)|\s)$/)[0]
this code only works with a specific format. If input format changes, we need to change it here. 
How about this? This isnt the best but the change is minimal and it works with any formats
```diff
diff --git a/webui/react/src/components/ProjectCard.tsx b/webui/react/src/components/ProjectCard.tsx
index d4729e7a1..c3e4d7b4f 100644
--- a/webui/react/src/components/ProjectCard.tsx
+++ b/webui/react/src/components/ProjectCard.tsx
@@ -81,7 +81,7 @@ const ProjectCard: React.FC<Props> = ({
                 <TimeAgo
                   className={css.lastExperiment}
                   datetime={project.lastExperimentStartedAt}
-                  tooltipFormat="[Last experiment started ]MMM D, YYYY - h:mm a"
+                  tooltipFormat="[Last experiment started \n]MMM D, YYYY - h:mm a"
                 />
               )
             )}
diff --git a/webui/react/src/components/TimeAgo.tsx b/webui/react/src/components/TimeAgo.tsx
index 1d12e7e2b..99af35bf5 100644
--- a/webui/react/src/components/TimeAgo.tsx
+++ b/webui/react/src/components/TimeAgo.tsx
@@ -116,7 +116,12 @@ const TimeAgo: React.FC<Props> = ({
   }, [updateInterval]);
 
   return (
-    <Tooltip content={dayjs(milliseconds).format(tooltipFormat)}>
+    <Tooltip
+      content={
+        <div style={{ whiteSpace: 'pre-wrap' }}>
+          {dayjs(milliseconds).format(tooltipFormat).replace('\\n', '\n')}
+        </div>
+      }>
       <div className={classes.join(' ')}>{durationString}</div>
     </Tooltip>
   );
```

2023-09-28 16:45 UTC, keita-determined approved these changes

2023-09-28 16:56 UTC, merged