feat: add RadioGroup to UI kit
determined-ai/determined pull request #8159
Opened 2023-10-16 19:38 UTC by thiagodallacqua-hpe

## Description

Ticket: WEB-1257

Add `RadioGroup` into the UI kit.

## Test Plan

- Go to the `/design/#RadioGroup` page

![Screen Shot 2023-10-16 at 16 36 19](https://github.com/determined-ai/determined/assets/104855841/86fbeeb8-6368-4cfb-9009-838d8597286f)

![Screen Shot 2023-10-16 at 16 48 37](https://github.com/determined-ai/determined/assets/104855841/f305f238-2f73-4e43-bce4-f5016eee0efa)

## Commentary (optional)

## Checklist

- [ ] Changes have been manually QA'd
- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
  See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-notes/README.md) for details.
- [ ] Licenses should be included for new code which was copied and/or modified from any external code.

## Ticket

2023-10-16 21:49 UTC, keita-determined requested changes

2023-10-16 21:49 UTC, keita-determined commented on webui/react/src/pages/Clusters/ClustersQueuedChart.tsx
> +  const options = [
Do we want this border? We dont have that in the current radio buttons

<img width="177" alt="image" src="https://github.com/determined-ai/determined/assets/109113616/0cf8e5ce-23b6-49c2-b155-d0a8522e6142">

2023-10-16 21:49 UTC, keita-determined commented on webui/react/src/components/kit/RadioGroup.tsx
> +interface Props extends Omit<RadioGroupProps, 'onChange' | 'options'> {
Some props are overlapped with `RadioGroupProps`

2023-10-16 21:49 UTC, keita-determined commented on webui/react/src/components/kit/RadioGroup.tsx
bug: 2 borders

<img width="635" alt="image" src="https://github.com/determined-ai/determined/assets/109113616/33a25138-4782-4929-9ef6-488b71430851">

2023-10-17 19:58 UTC, keita-determined commented on webui/react/src/components/kit/RadioGroup.tsx
> +interface Props extends Omit<RadioGroupProps, 'onChange' | 'options'> {
Then `onChange` doesn't have to be omitted??
Anyways what i meant is that we should follow the other components. Most of UIKit components don't extend props with antd props

2023-10-18 21:27 UTC, ashtonG commented
quick note: please remember to remove/replace the dependencies on `ConditionalWrapper` and `useResize` on the module -- these currently rely on stuff outside the UI Kit which will not be in the new repo.

2023-10-26 19:56 UTC, ashtonG commented on webui/react/src/pages/Clusters/ClustersQueuedChart.tsx
> +            value={String(viewDays)}
can we just allow the value to be a number or string?

2023-10-30 16:05 UTC, closed without merging