docs: Improve qs for webui user
determined-ai/determined pull request #8608
Opened 2023-12-19 21:27 UTC by tara-det-ai

## Description

Provide instructions for the WebUI user who wants to run an experiment.

The new WebUI user has just signed in to their Determined cluster. They don't know how to get started. They want to create an experiment using their own code. They are provided a link to a quickstart.

## Checklist

- [ ] Changes have been manually QA'd

## Test Plan

- [ ] Set up hosted Determined cluster and create a new user.
- [ ] Launch WebUI as the new user. 
- [ ] WebUI shows no experiments and provides user with link to a quickstart.
- [ ] Click the quickstart.
- [ ] Steps are reproducible.

2024-01-11 17:05 UTC, prevuri-determined requested changes

2024-01-11 21:34 UTC, tara-det-ai commented on docs/get-started/qs-webui.rst
> +      #. Install the Determined library and start a cluster locally:
resolved by adding a note similar to the remote instructions and by removing the extra instructions, keeping them only in the prerequisites section

2024-01-11 21:34 UTC, tara-det-ai commented on docs/get-started/qs-webui.rst
> +      #. In the WebUI dashboard, click the **Experiment** name to view the experiment’s trial
added

2024-01-11 21:34 UTC, tara-det-ai commented on docs/get-started/qs-webui.rst
> +         You can also use the ``-m`` option to specify a remote master IP address:
resolved as discussed

2024-01-11 21:34 UTC, tara-det-ai commented on docs/get-started/qs-webui.rst
> +         This is the number of available GPU resources. The ``slots_per_trial`` value must be
done

2024-01-11 21:34 UTC, tara-det-ai commented on docs/get-started/qs-webui.rst
> +      #. In the WebUI dashboard, click the **Experiment** name to view the experiment’s trial
added

2024-01-16 20:22 UTC, lbliii approved these changes

2024-01-23 17:37 UTC, closed without merging