fix: agent config precedence
determined-ai/determined pull request #8656
Opened 2024-01-08 17:25 UTC by amandavialva01

## Description
This PR makes determined-agent initialization and start-up more similar to determined-master by incorporating viper into agent configuration setup so ensure the correct priority of agent configuration options (flag > environment > config > default).

## Test Plan
- `cd` into local `determined` repo and spin up a cluster with the `devcluster` tool, adding `container_runtime: docker` to your devcluster config as follows: 
```
config_file:
   ...
    agent: 
         ...
         container_runtime: docker
```
- After spinning up the cluster, press `2` in your terminal to kill the agent binary so that we are only running `DB` and `MASTER`
- Open up a new terminal tab, cd into `determined/agent` and run `go build` to compile the `determined-agent` binary
- set the environment variable `DET_CONTAINER_RUNTIME=docker_cont`
- `cd` into `build` and run `./determined-agent --config-file /private/tmp/devcluster/agent.conf`
- verify that the `agent configuration` outputs shows `"container_runtime":"docker_cont"` rather than the default value `docker` 
- Now, to ensure that flags take precedent over defaults and environment variables, run `./determined-agent --config-file /private/tmp/devcluster/agent.conf --container-runtime docker_container`
- ensure that the `agent configuration` outputs shows `"container_runtime":"docker_container"` rather than the default value `docker` or the environment variable `docker_cont`

## Checklist

- [ ] Changes have been manually QA'd
- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
  See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-notes/README.md) for details.
- [ ] Licenses should be included for new code which was copied and/or modified from any external code.

## Ticket
DET-9800

2024-01-27 02:14 UTC, maxrussell requested changes
Looks really good! Thanks for taking this on. Couple things worth bringing up, but seems very close.

2024-02-06 22:05 UTC, amandavialva01 commented on agent/internal/options/options.go
> +		ContainerRuntime:       DockerContainerRuntime,
I mostly just hardcoded the default values for clarity, but changed this since it's a lot of redundant code.

2024-02-06 22:28 UTC, amandavialva01 commented on agent/internal/options/options.go
> +func (o *Options) ResolveHostname() (*Options, error) {
I like this, changed!

2024-02-07 23:52 UTC, maxrussell approved these changes

2024-02-08 16:43 UTC, merged