chore: fix console warning
determined-ai/determined pull request #8999
Opened 2024-03-14 17:23 UTC by thiagodallacqua-hpe

## Description

Ticket: ET-6

This PR will remain as a draft until the PR at the [hew repo](https://github.com/determined-ai/hew/pull/115) gets merged.
 

## Test Plan

## Commentary (optional)

## Checklist

- [ ] Changes have been manually QA'd
- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
  See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-notes/README.md) for details.
- [ ] Licenses should be included for new code which was copied and/or modified from any external code.

## Ticket

2024-04-23 20:53 UTC, keita-determined commented
which code?

2024-04-23 20:59 UTC, keita-determined reviewed
i still see warnings i listed in the ticket. not sure if i follow the changes. what are these changes for? and could you add test plans

2024-04-23 20:59 UTC, keita-determined commented on webui/react/src/components/ExperimentCreateModal.test.tsx
> +import { render, screen, waitFor } from '@testing-library/react';
why do we need `waitFor`?

2024-04-23 20:59 UTC, keita-determined commented on webui/react/src/components/JupyterLabModal.tsx
whats this change for?

2024-04-25 18:26 UTC, keita-determined requested changes
still see `Instance created by `useForm` is not connected to any Form element. Forget to pass `form` prop?` in admin page. could you check all modals.

---
`Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?` too in jupyter modal.

---

For the `validateDOMNesting` issue, reaching out to the code author might be a good idea

2024-04-25 18:26 UTC, keita-determined commented on webui/react/src/components/ExperimentCreateModal.tsx
> +    if (modalState.isAdvancedMode) form.validateFields(requiredFields); // initial disabled state set here, gets updated later in handleFieldsChange
qq: which console error does this code fix?

2024-04-25 19:51 UTC, keita-determined commented on webui/react/src/components/ExperimentCreateModal.test.tsx
> +import { render, screen, waitFor } from '@testing-library/react';
i tested without it and it worked

2024-04-25 20:09 UTC, keita-determined commented
@thiagodallacqua-hpe i tested in private mode, so i dont think its cache issue. Could you double check

<img width="1477" alt="image" src="https://github.com/determined-ai/determined/assets/109113616/2244cea4-609f-42f4-bb8e-a0ecc035655d">

<img width="1717" alt="image" src="https://github.com/determined-ai/determined/assets/109113616/9e32325c-7515-4cad-bc19-66adfb49486a">

2024-04-26 20:08 UTC, keita-determined requested changes
still see the warnings. could you ask someone to reproduce these before re-requesting the review?

https://github.com/determined-ai/determined/assets/109113616/1fee4780-cc61-4fc6-a293-a2d35b6931c8

2024-04-26 20:08 UTC, keita-determined commented on webui/react/src/components/ExperimentCreateModal.test.tsx
> +
nit: remove newlines

2024-04-29 14:37 UTC, johnkim-det commented
I am reproducing testing with local branch against latest-main API. FWIW I think I only see them once, and if I navigate away and back it doesn't show up. And then I see them again when I refresh the app.

2024-05-10 19:19 UTC, keita-determined commented
thanks for the fixes, but unfortunately, these warnings are still reproducible, and i dont thnk the jupyterlab modal warning isn't from antd based on the warning.
I'm open to pair to reproduce it, feel free to ping me anytime.

2024-09-26 14:12 UTC, closed without merging