feat: change RM Name to cluster name
determined-ai/determined pull request #9389
Opened 2024-05-20 13:31 UTC by amandavialva01

## Ticket
DET-10310

## Description
Referring to the RM in the master config by its `Name` rather than its corresponding `ClusterName` can be slightly misguiding given that the rest of the config provided for the given resource manager is cluster-specific. 
Referring to an RM by its Name implies that the underlying determined resource manager works independently of its corresponding cluster (so changing the cluster for an RM may not prompt an RM name change). However, this is not the case. Change the `Name` key to `ClusterName` to increase emphasis on the necessity of a specific cluster being tied to a given RM.

## Test Plan
CI Passes.

## Checklist

- [ ] Changes have been manually QA'd
- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
  See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-notes/README.md) for details.
- [ ] Licenses should be included for new code which was copied and/or modified from any external code.

2024-05-21 15:46 UTC, EmilyBonar reviewed
There are two more locations on web where the name needs to be changed:

1. Lines 145 and 146 in `ResourcePoolCard.tsx`
2. Line 128 in `stores/cluster.tsx`

2024-07-17 19:21 UTC, kkunapuli requested changes
Looks great! A couple small requests.

With this change, `name` will be ignored if it is set, right?

I think we should add a bit of validation to warn the user, if `name` is set. I think `Deprecations()` function might be a good place? https://github.com/determined-ai/determined/blob/274d7638f242364db2d64c2c6cb734839450d526/master/internal/config/config.go#L395 

Also, please update docs when you're ready! Please add a release note and update the master config reference.

2024-07-17 21:49 UTC, channolanp commented
When `additional_resource_managers[].resouce_manager.cluster_name` is omitted, the error message doesn't help lead the customer to the right solution:

> 	error found at root.ResourceConfig.AdditionalResourceManagersInternal[0].ResourceManager.KubernetesRM: name is required:  must be non-empty

That would make me think I should use `name` instead of `cluster_name`

2024-07-18 13:40 UTC, EmilyBonar approved these changes
Frontend side looks good!

2024-07-18 16:00 UTC, kkunapuli approved these changes
LGTM - nice work!

2024-07-18 17:15 UTC, tara-det-ai commented on docs/release-notes/deprecate-name-use-cluster-name.rst
> +-  Master: Add config field ``resource_manager.cluster_name`` and deprecate ``resource_anager.name``
```suggestion
- Master: Add config field ``resource_manager.cluster_name`` and deprecate ``resource_manager.name``
```

2024-07-18 17:28 UTC, tara-det-ai commented on docs/release-notes/deprecate-name-use-cluster-name.rst
> +            ``resource_manager`` section of your master configuration YAML.
:orphan

**Breaking Changes**

-  Master Configuration:  The ``resource_manager.name`` field is replaced by ``resource_manager.cluster_name`` for better clarity and to support multiple resource managers.
- Resource managers operate relative to the specific cluster providing resources for Determined tasks. - Changing the cluster will affect the resource manager's responses.
- The ``cluster_name`` must be unique for all resource managers when deploying multiple resource managers in Determined.
- During upgrade, replace ``name`` with ``cluster_name`` in the ``resource_manager`` section of your master configuration YAML.

2024-07-18 20:16 UTC, tara-det-ai commented on docs/reference/deploy/master-config-reference.rst
> +
do we know if these are known acronyms for our users: "singleRM" and "multiRM"

if not, we'll need to spell them out, e.g.,

Optional for single resource manager configurations. Required for multiple resource manager configurations.

2024-07-22 22:30 UTC, tara-det-ai approved these changes
LGTM

2024-07-22 22:32 UTC, merged