fix: update getProjectColumns calls (ET-270)
determined-ai/determined pull request #9509
Opened 2024-06-12 19:20 UTC by johnkim-det

## Ticket

ET-270

## Description

Primary task is to add `tableType` param usage to `getProjectColumns` calls (and handle new location types). Also includes other columns-related changes:
- Change initial filter state
- Make sure excluding columns from filter or sort actions works as intended
- Prefer column name from `getProjectColumns` API response over name from static front-end definition

## Test Plan

On all DataGrid components (`F_ExperimentList`, `FlatRuns`, `Searches`):
- Regression test for filtering, sorting, and column selection 
- Should consistently show same column names across column headers, filter menu, sort menu, and column selection menu.
- When filters are cleared and the Filters menu is opened, it should initially display a condition with an empty dropdown (not populated with "name")
- Banned filter columns ("searcherMetricsVal") should not have filter options in column header menus or show up in the Filter menu dropdown.
- Banned sort columns ("tags", "searcherMetricsVal") should not have sort options in column header menus or show up in the Sort menu dropdown.

## Checklist

- [ ] Changes have been manually QA'd
- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
  See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-notes/README.md) for details.
- [ ] Licenses should be included for new code which was copied and/or modified from any external code.

2024-06-14 17:00 UTC, johnkim-det commented
realize that FE test coverage number is below 80%, but it does look like that's mostly due to changes to page components where unit tests may not make as much sense, and also includes non-Flat Runs-specific changes. but definitely willing to add more tests if anyone has thoughts on where to add coverage.

2024-06-17 18:12 UTC, EmilyBonar requested changes
Mostly looks good except for terminology.

2024-06-17 21:38 UTC, johnkim-det commented on webui/react/src/pages/FlatRuns/columns.ts
> +    title: 'Experiment Description',
updating and confirming with piyush about what these should actually be called

2024-06-17 22:57 UTC, keita-determined reviewed
lgtm. please wait for Emily's additional review

2024-06-18 18:58 UTC, AmanuelAaron approved these changes
BE changes LGTM

2024-06-20 17:18 UTC, merged