feat: Add selection label to FlatRuns page
determined-ai/determined pull request #9548
Opened 2024-06-20 18:47 UTC by thiagodallacqua-hpe

## Ticket: [ET-309](https://hpe-aiatscale.atlassian.net/browse/ET-309)

## Description

Add the selection label to the flat runs table.

## Test Plan

- Enable the Flat runs feature
- go to a runs table
  - there should be a label with the total number of runs
- make a selection
  - the label should be updated accordingly 

![Screenshot 2024-06-20 at 15 48 22](https://github.com/determined-ai/determined/assets/104855841/c85537b9-406e-4d5f-8e2f-1ea09c6cba95)

![Screenshot 2024-06-20 at 15 48 12](https://github.com/determined-ai/determined/assets/104855841/5840a6a7-7b9e-4ed5-b996-2cd66e8fb001)

## Checklist

- [ ] Changes have been manually QA'd
- [ ] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
  See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-notes/README.md) for details.
- [ ] Licenses should be included for new code which was copied and/or modified from any external code.

[DET-123]: https://hpe-aiatscale.atlassian.net/browse/DET-123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-252]: https://hpe-aiatscale.atlassian.net/browse/ET-252?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ET-309]: https://hpe-aiatscale.atlassian.net/browse/ET-309?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-06-20 22:46 UTC, keita-determined requested changes
formatting and linting code is missing

2024-06-20 22:46 UTC, keita-determined commented on webui/react/src/pages/FlatRuns/FlatRuns.tsx
> +    }
this code might causes unintentional value change, so this needs to be fixed

2024-06-20 22:46 UTC, keita-determined commented on webui/react/src/pages/FlatRuns/FlatRuns.tsx
> +        let label = `${totalExperiments.toLocaleString()} ${pluralizer(
we can use `const` by refactoring code

2024-06-24 18:30 UTC, keita-determined commented on webui/react/src/pages/FlatRuns/FlatRuns.tsx
> +    }
i think this is not fixed

2024-06-26 18:45 UTC, keita-determined requested changes
its getting close

2024-06-26 18:45 UTC, keita-determined commented on webui/react/src/pages/FlatRuns/FlatRuns.tsx
> +    const numberOfSelection = runsList.length;
actually we dont need to assign the array because we just wanna know the length.

2024-06-26 18:45 UTC, keita-determined commented on webui/react/src/pages/FlatRuns/FlatRuns.tsx
> +              <span className={css.runSelection} data-test="runSelection">
can we add test cases?

2024-06-28 19:02 UTC, keita-determined commented on webui/react/src/pages/FlatRuns/FlatRuns.tsx
> +              <span className={css.runSelection} data-test="runSelection">
i think tests need to be in the same PR. AFAIK, that's what we agreed in the meeting for the reliability

2024-06-28 19:06 UTC, keita-determined reviewed
can we add tests? (80% or more code cov)

2024-06-28 19:06 UTC, keita-determined commented on webui/react/src/pages/FlatRuns/FlatRuns.tsx
> +          'runs',
nit: i think we can remove the 3rd arg

2024-07-17 19:19 UTC, johnkim-det commented
closing and replacing with https://github.com/determined-ai/determined/pull/9670

2024-07-17 19:19 UTC, closed without merging