feat: show metadata in run table
determined-ai/determined pull request #9776
Opened 2024-07-31 21:21 UTC by keita-determined

## Ticket

[ET-222]

## Description

Show metadata in the run table.
have not excluded the array type columns yet. will implement it after #9759 is merged, but its not a blocker to merge this PR.

## Test Plan

- go to run table
- click `Columns` button and see `Metadata` tab. user should be able to add metadata columns and filter and sort by metadata (metadata with array type are not supported for filtering and sorting, PR will come after #9759 to exclude the array type metadata in filter and sort)

## Checklist

- [ ] Changes have been manually QA'd
- [ ] New features have been approved by the corresponding PM
- [ ] User-facing API changes have the "User-facing API Change" label
- [ ] Release notes have been added as a separate file under `docs/release-notes/`
  See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-notes/README.md) for details.
- [ ] Licenses have been included for new code which was copied and/or modified from any external code

2024-08-01 18:06 UTC, EmilyBonar requested changes
![Screenshot 2024-08-01 at 14-03-45 Uncategorized Runs - Determined](https://github.com/user-attachments/assets/881c0440-19cd-4848-9c98-4aec7b9eace5)
This is really bad UX, needs some design work to figure out correct solution.

2024-08-01 19:57 UTC, keita-determined commented on webui/react/src/pages/FlatRuns/FlatRuns.tsx
> +          case V1LocationType.RUNMETADATA:
fixed it

2024-08-01 19:57 UTC, keita-determined commented
@EmilyBonar 
<img width="484" alt="image" src="https://github.com/user-attachments/assets/d27dc326-3771-466f-a354-50dc930fd21a">

fixed it

2024-08-01 19:58 UTC, keita-determined commented on webui/react/src/components/ColumnPickerMenu.module.scss
> +@media only screen and (width <= 390px) {
looks like `$breakpoint-` variables are not working so use the constant number

2024-08-02 16:52 UTC, EmilyBonar approved these changes
LGTM

2024-08-02 17:09 UTC, merged