fix: Remove CSS rule for hiding the Form.Item error message
determined-ai/determined pull request #9872
Opened 2024-08-27 20:14 UTC by thiagodallacqua-hpe

## Ticket

[ET-70](https://hpe-aiatscale.atlassian.net/browse/ET-70)

## Description

There's a bug where, when you try to submit a form with errors, the error feedback messages won't show bellow the form items.

This PR intends to fix that.

## Test Plan

- Open a modal with a form.
- try submitting with an error (like not filling a required field)
- the message should appear bellow the form item.

![Screenshot 2024-08-27 at 17 10 20](https://github.com/user-attachments/assets/6accd93d-e895-4561-b391-6dafdf6fd0d3)

## Checklist

- [ ] Changes have been manually QA'd
- [ ] New features have been approved by the corresponding PM
- [ ] User-facing API changes have the "User-facing API Change" label
- [ ] Release notes have been added as a separate file under `docs/release-notes/`
  See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-notes/README.md) for details.
- [ ] Licenses have been included for new code which was copied and/or modified from any external code

[ET-70]: https://hpe-aiatscale.atlassian.net/browse/ET-70?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DET-123]: https://hpe-aiatscale.atlassian.net/browse/DET-123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-08-27 20:33 UTC, keita-determined submitted a review, later dismissed
found layout issues

2024-08-27 20:33 UTC, keita-determined commented on webui/react/src/components/HyperparameterSearchModal.module.scss
> -    :global(.ant-form-item-explain) {
i think we wanna hide error message only in HP search, but wanna show it somewhere else. 
This issue cause this layout issue

<img width="1014" alt="image" src="https://github.com/user-attachments/assets/1093ef4a-4e7e-4ab0-b149-bb3f908e3082">

2024-09-06 19:50 UTC, ashtonG requested changes

2024-09-06 19:50 UTC, ashtonG commented on webui/react/src/components/HyperparameterSearchModal.module.scss
> +    div[class*='ant-form-item-explain'] {
This doesn't fix the issue. Error messages on non hyperparameter search modals are still hidden.

2024-09-16 15:20 UTC, ashtonG commented on webui/react/src/components/HyperparameterSearchModal.module.scss
> +        div[class*='ant-form-item-explain'] {
can we just use a class selector? this is only 1 point more specific than `.ant-form-item-explain` but will make our lives harder when trying to search for specific css selectors in the future.

2024-09-18 17:05 UTC, ashtonG commented on webui/react/src/components/HyperparameterSearchModal.module.scss
> +        div[class*='ant-form-item-explain'] {
ah i think i got it, try 
```suggestion
        :global(.ant-form-item-explain) {
```
otherwise the class will be hashed.

2024-09-20 14:55 UTC, ashtonG approved these changes

2024-09-20 14:56 UTC, merged